usdoj-crt/beta-ada

_includes/footer.html
_includes/phone.html
package-lock.json

Adds an area for photo attribution to the footer.

Add image attribution in footer

---

_includes/alert.html
index.html

Removed html for alert section from the homepage and created a new alert include file.

Created alert include

---

_includes/card.html
_pages/index.md

Removes card markup from homepage and creates reusable card include.

Create card include

---

_includes/banner.html
_pages/understanding/parking.md
_pages/understanding/service-animals.md
search/index.html

Resolving accessibility issues picked up by pa11y-ci.

a11y fixes

---

_assets/css/custom/page.scss
_config.yml
_pages/index.md
_pages/understanding/intro-to-ada.md

Allows things like paragraphs and lists to be rendered within HTML tags.

Parse markdown within HTML blocks

---

_assets/css/custom/page.scss
_includes/alert.html
_pages/report/index.md
_pages/understanding/index.md
_pages/understanding/parking.md
_pages/understanding/service-animals.md

Adjusts existing HTML to parse markdown correctly based on the changes in https://github.com/usdoj-crt/beta-ada/pull/76

Clean up markdown for block level parsing

---

_config.yml
_includes/menu.html
_pages/index.md

Enable link to https://civilrights.justice.gov/report/ where appropriate.

Add report link

---

_pages/index.md

Add learn more button to landing page history section

---

_assets/css/custom/_header.scss
_config.yml
_includes/logo.html

Update beta tag

---

_assets/css/custom/_all.scss
_assets/css/custom/_page.scss
_assets/css/custom/_sidenav.scss
_assets/css/custom/_utilities.scss
_assets/js/main.js
_config.yml
_includes/scripts.html
_layouts/page.html
package-lock.json
package.json

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/89

Add sticky nav and scroll spy

---

_assets/css/custom/_all.scss
_assets/css/custom/_page.scss
_assets/css/custom/_utilities.scss
_pages/guides/intro-to-ada.md

- Restructures Introduction to ADA content based on first round of research

Restructures Intro to ADA content based on user research

---

_pages/guides/parking.md

- Applies DRS style guide (mostly title case, percent format, and bullet caps) to parking overlay

Applies DRS style guide to Parking overlay

---

.github/workflows/test.yml
.htmlvalidate.json
_includes/banner.html
_includes/scripts.html
_layouts/redirect.html
package-lock.json
package.json

Also resolves a few things `html-validate` caught.

Integrate html-validate into CI workflow

---

_pages/guides/intro-to-ada.md

See: https://github.com/usdoj-crt/beta-ada/pull/97#issuecomment-829743794
Good catch, @lauraponce

Remove details element

---

_includes/sidenav.html
_pages/guides/parking.md
_pages/index.md

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/170

Hide parking content

---

_pages/guides/intro-to-ada.md

@kstitch7 wanted a preview that incorporated both the clean title headings on Intro to ADA (omits title name from headings), and the new details element styling, so I spun up this branch.
We also don't have the clean titles in a mergeable branch, since those changes were combined with the banner test. So this branch will make those edits available to `main`.

Clean intro accordion headings

---

_assets/css/custom/_all.scss
_assets/css/custom/_details.scss
_assets/css/custom/_page.scss
_assets/images/book.svg
_pages/guides/intro-to-ada.md
_pages/guides/service-animals.md
_plugins/details.rb

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/160
Implements the accordion-like `<details />` block described in https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/84
The tag can be used in markdown files using the following syntax:
```
{% details What does <i>major life activities</i> mean? %}
Major life activities are the kind of actions that you do every day, including your body’s own internal processes. There are many major life activities in addition to the examples listed here. Some examples include:
- Actions like eating, sleeping, speaking, and breathing
- Movements like walking, standing, lifting, and bending
- Cognitive functions like thinking and concentrating
- Sensory functions like seeing and hearing
- Tasks like working, reading, …
```

Implement Additional Context custom tag 

---

_pages/guides/parking.md

- Fixes broken link to 2010 ADA standards and clarifies link text
- Converts images to block elements (from grid)

Parking edits and image refactoring

---

_config.yml
_includes/landing/history.html
_includes/landing/report.html
_includes/landing/understand.html
_pages/index.md

- Info line and @kstitch7 edits to homepage content

KS edits to homepage

---

_assets/css/custom/_page.scss
_config.yml
_pages/guides/mobility-devices.md
_pages/guides/parking.md
_plugins/icon_list.rb

I think the detais/summary re assurances is too close to the red x.  Take a look.

Mobility devices

---

_assets/css/custom/_page.scss
_layouts/page.html

Remove extra spacing in mobile menu.

Update margin/padding for mobile table of contents menu

---

_assets/js/main.js
_config.yml
package-lock.json
package.json

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/101

Add automatic anchor links to headings on hover

---

_assets/css/_uswds-theme-components.scss
_assets/css/custom/_accordion.scss
_assets/css/custom/_all.scss
_assets/css/custom/_details.scss
_assets/images/add--primary.svg
_assets/images/remove--primary.svg

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/85

Update styles for title accordions

---

_includes/landing/hero.html
_pages/index.md

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/172

Add alt text to mobile and desktop hero images

---

_includes/footer.html

Brian, I coded DRS the same as CRT.  Let me know if I should modify to a subheading.  And of course if I need to fix anything else.  I'd be glad to redo this process for accuracy but also training.  I wasn't able to preview it until now.  
Thanks!

Modified phone numbers and added DRS

---

_pages/topics/intro-to-ada.md

- Edits Intro to ADA based on quality control governance process

Intro to ADA QC edits

---

_includes/alert.html
_layouts/page.html

To be removed prior to launch.

Remove legal disclaimer

---

_pages/topics/intro-to-ada.md
_pages/topics/mobility-devices.md
_pages/topics/parking.md
_pages/topics/service-animals.md

- Adds `description` key and values to topic page front matter
- Edits "nonprofit" to "non-profit" (as written in DRS style guide)
Added custom descriptions to all topic pages (not just beta release pages).

Adds page meta descriptions for topics

---

_config.yml
_pages/index.md

- Edits homepage title from `Home` to `The Americans with Disabilities Act`
- Adds description field to homepage

Edits title and adds description for homepage

---

_assets/css/custom/_all.scss
_assets/css/custom/_banner-beta.scss
_assets/css/custom/_banner.scss
_assets/css/custom/_footer.scss
_assets/css/custom/_header.scss
_config.yml
_includes/banner-beta.html
_includes/footer.html
_includes/header.html
_includes/logo.html

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/183

Add beta banner and back link

---

_includes/footer.html

- Removes copy preceding TTY number
- ~~Adds link to Disabled And Here project page (as directed by the [image usage and credit page](https://affecttheverb.com/usage/))~~

Edits footer TTY copy

---

_config.yml

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/199

Add home link to global nav

---

_assets/css/custom/_all.scss
_assets/css/custom/_modal.scss
_assets/js/main.js
_assets/js/modal.js
_assets/js/redirect-modal.js
_includes/footer.html
_includes/redirect-modal.html
_layouts/default.html

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/173
Launches a modal when links containing the `external-link--popup` class are clicked.

Add exit notification modal

---

_assets/css/custom/_all.scss
_assets/css/custom/_print.scss
_assets/js/main.js
_assets/js/print.js

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/205
Adds a print stylesheet to simplify and increase readability of printed pages:

Add print stylesheet

---

_assets/css/_uswds-theme-components.scss
_assets/css/_uswds-theme-utilities.scss
_assets/css/custom/_all.scss
_assets/css/custom/_page.scss
_assets/css/custom/_pagination.scss
_assets/css/custom/_utilities.scss
_assets/js/main.js
_assets/js/search.js
_config.yml
_includes/logo.html
_includes/menu.html
_includes/pagination.html
_includes/searchgov/form.html
_pages/search.md
package-lock.json

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/242
Connects the beta site to the `justice-ada-beta` search.gov instance via the search box in the header. As of right now no content is being indexed, so no results will show.

Add search support

---

_assets/css/_uswds-theme-components.scss
_assets/css/overrides/_hero.scss
package-lock.json

Hotfix to resolve issue with landing page background image

Fix hero image background

---

_pages/search.md

Follow up work on search.gov integration to allow support for best bets.

Enable search.gov best bets via REST API

---

_pages/topics/service-animals.md

Changes `Service animals` to `Service Animals` in topic card to conform to DRS style guide

Changes card heading to title case

---

_config.yml
_includes/landing/report.html
_includes/landing/understand.html
_pages/file-a-complaint.md
_pages/topics/index.md

- Minor edits to page and section titles for consistency

Edits copy for consistency

---

_pages/topics/mobility-devices.md

added alt text

---

_includes/footer.html

- Changes link text to `File a complaint`
- Changes link destination to intermediary complaint page

Updates footer "complaint" link

---

_pages/topics/intro-to-ada.md
_pages/topics/service-animals.md

- We've observed in user research that each 'overlay' card starting out with "Find out..." is distracting to users. This change breaks with that format and introduces a short description in an alternative format for Intro and Service Animals cards.

Edits card copy for intro and service animals

---

_assets/css/_uswds-theme-utilities.scss
_assets/css/custom/_utilities.scss
_pages/law-and-regs/ada.md

- Adds custom margin levels to extend USWDS pattern
- Applies more aggressive indents for use on ADA statute
- Crosswalks margin styles for statute indent
[Preview 🔍 ](https://federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.app.cloud.gov/preview/usdoj-crt/beta-ada/rj-law-margins/law-and-regs/ada/)

Adds margin levels for statute indents

---

_pages/file-a-complaint.md
_pages/topics/intro-to-ada.md

revised link in intro and made copy edit in filing a complaint

made two minor edits

---

_assets/css/custom/_pagination.scss
_pages/search.md

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/281

Fix for search pagination links

---

_config.yml
_includes/landing/understand.html
_pages/topics/index.md
_pages/topics/intro-to-ada.md

Make Intro to ADA first in the list of cards, and simplified card sorting logic.

Reorder ADA Topic cards

---

_pages/index.md

Adds missing punctuation to `We‘ll add more soon` on homepage.

Adds missing punctuation to home independent clause

---

_assets/css/custom/_utilities.scss
_includes/touchpoints.html

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/292

Hide feedback button on mobile

---

_assets/css/_uswds-theme-utilities.scss
_assets/css/custom/_buttons.scss
_assets/js/main.js
_assets/js/print-button.js
_includes/print-button.html
_layouts/page.html
_pages/_topics/effective-communication.md
_pages/_topics/intro-to-ada.md
_pages/_topics/mobility-devices.md
_pages/_topics/parking.md
_pages/_topics/service-animals.md

Added print functionality via Javascript.
Added styling to hide button on mobile devices.
Added print flag to topics pages so that button is displayed.

Print button

---

_assets/js/main.js
_assets/js/scroll-into-view.js
_assets/js/skip-content-links.js
_includes/skipnav.html
_layouts/page.html

Added dummy divs and and javascript

Chrome Sidenav/Main Content Bug Fix

---

.github/workflows/linter.yml

Updated to version 4.
Change in: /beta-ada/.github/workflows/linter.yml
Updated line 64 to `uses: github/super-linter@v4.0.2` from `uses: github/super-linter@v3`

Super linter update

---

_assets/js/pagination.js
_assets/js/templates/pagination/paginationTemplate.js
_assets/js/utils/applyFocusStyling.js
_assets/js/utils/createRange.js
_assets/js/utils/paginationLogic/index.js
_assets/js/utils/renderSearchPage.js

Three main changes: Removed lingering arrow funcs, capped results at 1000 and made sure that the search pages end at the right spot.
Closes: https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/372

Fix Last page of results no results bug

---

_pages/notices/_posts/2021-08-25-covid-qa.md

text edit and added hyperlink in question 5.

edit to question 5

---

package-lock.json
package.json

Changes:
1. Updated to USWDS 2.13.1 in `package.json`

Updating to USWDS 2.13.1

---

_pages/notices/_posts/2021-08-25-covid-qa.md

Changes:
1. Updated the `notice_text_es` field in the front matter of the COVID QA page. 
To Test:
1. View the Spanish translation page of the File a Complaint page. The new text: "El COVID-19 y la ley de Estadounidenses con Discapacidades – visualizar información sobre políticas para visitantes a entornos médicos y restaurantes en la calle" will be presented there.

New COVID notice Spanish translation text

---

_includes/header.html

Change: Removed dang pesky double quotes from language selector in `header.html`.

Alt tag fix for close button.

---

_assets/css/custom/_all.scss
_assets/css/custom/_file-a-complaint.scss
_assets/css/custom/_typography.scss
_assets/css/mixins/_typography.scss
_pages/es/presente-una-queja.md
_pages/file-a-complaint.md

1. Changes:
- Added new text to the file a complaint page
- Added styling to match @chinelo-ikejimba's designs
- Did my best to match the text in presente una queja page.
2. Test:
- Confirm that the page in the preview link matches the design mockup provided by Chinelo
- Confirm that the Spanish language page matches the styling
[Here is the mockup](https://user-images.githubusercontent.com/92807659/159792573-e2fc137e-00df-405b-bd24-f44b0dd3f4b7.png)

Added new text and formatting for file a complaint copy

---

_assets/css/_uswds-theme-components.scss
_assets/css/_uswds-theme-spacing.scss
_assets/css/custom/_landing.scss
_includes/footer.html
_includes/landing/hero.html
_layouts/page.html

Page margins have been shrunk down.
Tests:
1. Visual inspection on desktop devices - Passed
2. Visual inspection on tablet width devices - Passed
3. Visual inspection on mobile width devices - Passed
Deployment plan:
1. Page Margin Decrease
2. Global Navigation renaming
3. TA Landing page
4. Breadcrumbs

Page Margin decrease

---

_pages/_resources/service-animal-faqs.md
_pages/_resources/service-animals-2010-requirements.md

Super small fix - removed permalinks from ADA Requirements: Service Animals and Frequently Asked Questions about Service Animals.
This fixes URL issues. Links and everything still work, the URLs on the pages are not accurate though.

Small change to fix routing with sa ta pages.

---

_pages/_resources/service-animal-faqs.md
_pages/_resources/service-animals-2010-requirements.md
_pages/_topics/service-animals.md

edited links in SA overlay to point to beta TA and edited Resources sections in SA TA pieces.

saoverlay link edit

---

_assets/js/main.js
_assets/js/print-button.js
_includes/scripts.html
webpack.config.js

The print-button.js script has been removed from the main.js file, and is now built by Webpack and pulled into the scripts.html template on it's own.
To Test:
1. Navigate to one of the pages in the 'Explore Featured Topics' section 
2. Click the "Print this page" button
3. Each page should print
4. Confirm there are no errors thrown to the console.

Moving Print Button JS over to wepback.

---

_assets/js/templates/badges/attachBadge.js
_assets/js/utils/taSelectors/countVisibleArticles.js
_assets/js/utils/taSelectors/toggleVisibility.js
_assets/js/utils/taSelectors/updateDomAndURL.js
_includes/ta-article-list.html
tests/menu-button-mobile.spec.js
tests/ta-landing-page.spec.js

[Ticket](https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/515)
The filter on the Resources page currently operates as an 'OR' filter, meaning that it looks for items with a tag or any other tag in the filter. This can yield slightly confusing results where the filter returns a whole bunch of stuff. This change makes the filter into an 'AND' filter. Meaning that if multiple tags are selected, it finds items that match all of the tags.
Other changes: 
1. Tags are being put into data attributes rather than in the class list. This will prevent any future collisions.
2. Playwright tests have been updated.
Old:
New:
+ [x] Confirm that all items appear when selecting ONLY one of the Organization Checkboxes
+ [x] Confirm that all items appear when selecting BOTH of the …

Change Resources list filter from 'OR' to 'AND'

---

admin/config.yml

Can you make sure the optional fields looks right to you and see that update and creates with images are working?

Update optional fields add public directory for images

---

_pages/_topics/telehealth.md
_pages/_topics/voting.md

Changes: 
Voting and Telehealth overlays have been added to the News widget on the homepage.

Adding voting and telehealth overlays to hompage

---

_pages/_topics/child-care-centers.md
_pages/_topics/parental-rights.md

Changes:
Added Parental Rights overlay and Child Care Centers overlay to home page news widget.

Adding child care centers and parental rights to homepage news widget.

---

_pages/_topics/child-care-centers.md
_pages/_topics/effective-communication.md
_pages/_topics/mobility-devices.md
_pages/_topics/parking.md
_pages/_topics/title-ii.md
_pages/_topics/title-iii.md

Changes: 
All tags are now added to the topics pages. Related content boxes have been added to each overlay as well.

Added all tags to topics pages and updated links to primers.

---

_config.yml
_pages/_resources/ai-guidance.md
_pages/_resources/child-care-centers.md
_pages/_resources/disability-rights-guide.md
_pages/_resources/effective-communication.md
_pages/_resources/medical-care-mobility.md
_pages/_resources/opdmds.md
_pages/_resources/restriping-parking-spaces.md
_pages/_resources/service-animal-faqs.md
_pages/_resources/service-animals-2010-requirements.md
_pages/_resources/title-ii-primer.md
_pages/_resources/title-iii-primer.md
_pages/es/presente-una-queja.md
_pages/file-a-complaint.md
_pages/infoline.md

Info Line TTY number updated to 202-514-0383.

Updated infoline TTY number

---

_includes/related-content.html
_pages/_resources/ai-guidance.md
_pages/_resources/child-care-centers.md
_pages/_resources/disability-rights-guide.md
_pages/_resources/effective-communication.md
_pages/_resources/medical-care-mobility.md
_pages/_resources/opdmds.md
_pages/_resources/restriping-parking-spaces.md
_pages/_resources/service-animal-faqs.md
_pages/_resources/service-animals-2010-requirements.md
_pages/_resources/web-guidance.md
_pages/_topics/telehealth.md
_pages/_topics/title-ii.md
_pages/_topics/title-iii.md
_pages/law-and-regs/title-ii-2010-regulations.md
_pages/law-and-regs/title-iii-regulations.md

@c2nelson I made a decision here that I want your input on.
We applied the title ii and title iii tags to all content on the site, and this was because those topics apply to everything. I think we should consider being more selective with these tags, since the idea of the tags is to determine relationships and exclude content.
So, I made a rough guess at which items should be related to each other by title ii and iii. We should walk through these changes together.

Retagging and adding related content [WIP]

---

_pages/notices/_posts/2022-11-02-upcoming-changes.md

@c2nelson @vwilliamsn Including the revised launch text about Technical Assistance docs.

Update launch text in notice page

---

_pages/notices/_posts/2022-11-02-upcoming-changes.md

Can't seem to merge in the PR she opened, so I repeated the changes here.

Adding in Allison Norman's edits

---

_pages/_resources/2021-08-25-covid-qa.md
_pages/redirects/covid-19.md

Changes: 
1. Created new redirect for old covid notice
2. Updated covid redirect for resources page

Fixing covid beta redirect

---

_includes/footer.html
_includes/phone.html
_pages/404.md
_pages/law-and-regs/index.md

Super small edits. Changed the border radius on the info line box and fixed the spacing on mobile in the footer. 
I also added a period on the 404 page and the Design Standards landing page.

Fixed footer styling and infoline styling. Added small edits.

---

_pages/index.md

Offical changed to Official

---

_pages/redirects/508_report.md

modified 2012 508 report redirect

modified redirect

---

_includes/meta.html
_includes/scripts.html
_layouts/default.html

I removed conflicting Google Analytics script tags and removed the existing configuration variables. Otherwise analytics is left as is.

Cleaning up google analytics

---

_assets/sass/custom/_site_alert.scss
_assets/sass/styles.scss
_includes/notice.html
_pages/notices/_posts/2022-11-16-ada-launch.md

@nguyen-tina Please use the preview link to review the styling.
Once that is approved we can merge this in and make it live.

Homepage alert site redesign

---

_pages/_topics/community-integration.md
_pages/_topics/emergency-planning.md
_pages/notices/_posts/2022-11-16-ada-launch.md

switched news items and promoted overlays

overlays news

---

_assets/js/redirect404.js
_assets/sass/custom/_site_alert.scss
_includes/alert.html
_includes/common-alert.html
_includes/ta-link-back.html
_layouts/full.html
_layouts/page.html
_pages/404.md
_pages/resources.md

Duplicate of #464 to get CI to run

[Duplicate of #464]

---

_pages/_topics/emergency-planning.md

fixed typo and links

---

_pages/law-and-regs/design-standards/2010-stds.md

added heading to 904

---

_pages/_resources/accessible-pools-requirements.md
_pages/_resources/child-care-centers.md
_pages/_resources/disability-rights-guide.md
_pages/_resources/effective-communication.md
_pages/_resources/law-enforcement-guide.md
_pages/_resources/medical-care-mobility.md
_pages/_resources/opdmds.md
_pages/_resources/restriping-parking-spaces.md
_pages/_resources/service-animal-faqs.md
_pages/_resources/service-animals-2010-requirements.md
_pages/_resources/ticket-sales.md
_pages/_resources/title-ii-primer.md
_pages/_resources/title-iii-primer.md

@vwilliamsn I added the language and verified dates.  lI'd like to review this together.

fixed typo and added language

---

_pages/_topics/opioid-use-disorder.md

The OUD topic has broken links to a PDF. This fixes them to point to OUD guidance, instead.

Fix Broken OUD Links

---

_config.yml

Reorders nav to be in order of increasing technical complexity:

Move laws and regs after resources

---

_pages/law-and-regs/index.md

We'll need to investigate more broadly what changed to make this a problem.

Fix Title II Link

---

_pages/_resources/title-ii-primer.md

fixed broken link and added a link t2 primer

---

_pages/_topics/community-integration.md
_pages/_topics/intro-to-ada.md
_pages/_topics/opioid-use-disorder.md

-took out superfluous paren in intro topic
-removed expired what's new content from widget

three quick edits

---

_data/tags.yml
_pages/_resources/2021-08-25-covid-qa.md
_pages/_resources/accessible-pools-requirements.md
_pages/_resources/child-care-centers.md
_pages/_resources/commonly-asked-questions-law-enforcement.md
_pages/_resources/medical-care-mobility.md
_pages/_resources/opdmds.md
_pages/_resources/opioid-use-disorder.md
_pages/_resources/q&a-accessibility-requirements-pools-public.md
_pages/_resources/restriping-parking-spaces.md
_pages/_resources/ticket-sales.md
_pages/_resources/web-guidance.md
_pages/_topics/child-care-centers.md
_pages/_topics/community-integration.md
_pages/_topics/mobility-devices.md
_pages/_topics/opioid-use-disorder.md
_pages/_topics/parental-rights.md
_pages/_topics/telehealth.md
_pages/_topics/voting.md

This PR updates page tags per the content grid to connect related pages.

Add page tags from content grid

---

_pages/law-and-regs/index.md

updated content on law and regs landing page

updated unified agenda info

---

_includes/page-type-info-box.html

Small wording change to the info box:

Update info box content

---

_assets/js/main.js
_assets/js/utils/gaUtil.js
_includes/page-type-info-box.html

This PR adds event tracking to the info box

Add click tracking to info box

---

_assets/js/netlify/genImageData.js
_assets/js/netlify/makeHTMLFromBodyContent.js
_assets/js/netlify/renderMdWidgets.js

This PR addresses a couple issues in Netlify:
1. When images were added in new PRs they were not rendering properly. This PR adds logic to get the paths for those images.
2. The detail includes component was not rendering properly where the text contained apostrophes. This PR adds logic to remove those so the components can be parsed properly and then add them back once they are parsed.

Fix new image loading and detail component

---

_pages/notices/_posts/2022-11-16-ada-launch.md

modified launch banner

---

_pages/law-and-regs/index.md

updated unified agenda content

---

_includes/notice.html

This PR updates the notice component to only show the h3 tag if there is notice text

Homepage notice fix

---

_includes/expand-button.html

This PR fixes the margin for the expand all button on mobile.
**Before**
**After**

Expand all - mobile spacing fix

---

_assets/js/templates/search/graphicBestBetsSectionTemplate.js
_assets/js/templates/search/graphicBestBetsTemplate.js
_assets/js/utils/renderSearchPage.js

Mock of new best bet box with links and no descriptions:

Add new best bet box type

---

_pages/_topics/service-animals.md
_pages/law-and-regs/ada.md
_pages/law-and-regs/index.md
_pages/law-and-regs/title-ii-2010-regulations.md
_pages/law-and-regs/title-iii-regulations.md
_pages/resources.md
_pages/topics.md

This PR updates the meta descriptions for the following pages:
/topics
/resources
/topics/service-animals
/law-and-regs
/law-and-regs/title-iii-regulations
/law-and-regs/title-ii-2010-regulations
/law-and-regs/ada

Update meta descriptions

---

_assets/js/templates/search/textBestBetsTemplate.js
_assets/js/utils/gaUtil.js
_includes/notice.html
_includes/page-type-info-box.html
_includes/related-content.html
_includes/subnav.html
_pages/file-a-complaint.md

This PR adds click tracking to the file a complaint page links and updates other tracked links to replace the aria-label attribute with a data-ga-event-name.

File a complaint click tracking

---

_assets/js/utils/gaUtil.js

This PR fixes a bug with the expand all button where it redirects to a 404.

Fix expand all

---

_assets/js/carousel.js

This PR fixes an issue where the carousel-nav class needed for GA click tracking was being removed in the JS.

Carousel GA tracking class fix

---

_pages/cases.md
_pages/file-a-complaint.md
_pages/infoline.md
_pages/search.md

This PR updates the meta descriptions per [this issue](https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/830).

Update landing page meta descriptions

---

_pages/law-and-regs/design-standards/2010-stds.md

fixed error in table 407 section

---

_assets/js/feature-flag.js
_assets/js/laws-regs-parser.js

This PR opens the law and regs feature flag to 100% public.

Open laws and regs feature

---

_pages/notices/_posts/2023-07-20-web-nprm.md

remove banner 

---

_pages/_resources/ballot-box-accessibility.md

spelling error in front matter

download pdf fix

---

_pages/law-and-regs/design-standards/2010-stds.md

Design standard edits

---

_assets/js/main.js
_assets/js/touchpoints-page-helpful.js
_assets/sass/custom/_touchpoints.scss
_includes/scripts.html
_includes/touchpoints-page-helpful.html
_layouts/default.html
_layouts/page.html
_pages/404.md
_pages/feedback.md
_pages/index.md
_pages/site_map.md
_pages/topics.md

This PR adds the "Was this page helpful" touchpoints question for pages with and without a sidenav.

Touchpoints yes/no poll

---

_assets/js/feature-flag.js
_assets/js/main.js
_assets/js/netlify/makeHTMLFromBodyContent.js
_assets/js/netlify/renderMdWidgets.js
admin/index.html

This PR fixes a bug in Netlify where **'** in the **asset** tags were causing them to produce an error. It also removes the laws and regs feature flag since that feature is fully launched

Debug netlify and remove feature flag

---

_pages/_resources/olmstead-employment-qa.md

@vwilliamsn - added FR link and language to page.  removed reference in description.

FR link added

---

_assets/js/dist/backToTop-compiled.js
_assets/js/dist/taResources-compiled.js
_pages/_resources/olmstead-employment-qa.md

removed news item from 10/31/23

removed news item

---

_pages/law-and-regs/title-iii-regulations.md

added space between (e) and (f) in &sect;36

added missing space b/t list

---

_pages/notices/_posts/2024-01-10-mde-nprm.md

The FR published the NPRM this morning.  Added published to banner and in text.

FR published nprm

---

.github/workflows/content-grid.yml
scripts/create_content_grid.sh

This PR adds a deployment date field to the content grid.
[content_grid.csv](https://github.com/usdoj-crt/beta-ada/files/14145153/content_grid.21.csv)

Add deployment date

---

_pages/_resources/ballot-box-accessibility.md

Changed heading to Ballot Drop Box Accessibility

Update Resources “ballot-box-accessibility”

---

_pages/_resources/accessible-cells.md

Small change in the accessible toilet drawing notes.

Update Resources “accessible-cells”

---

_pages/law-and-regs/index.md

Updated content related to unified agenda.

updated proposed changes content

---

_pages/law-and-regs/regulations/index.md

Also added proposed changes content to regs landing page

added proposed chgs content

---

_config.yml
_pages/_resources/child-care-centers.md
_pages/_resources/protecting-voter-rights.md
_pages/_resources/solutions-voting-problems.md
_pages/infoline.md

The ADA Information Line hours will change beginning 3/4.

upcoming info line hours

---

_pages/_resources/title-ii-primer.md

T2 Primer typo fix

---

_includes/footer.html

added link to dept.'s eeo policy statement in footer

added link to eeo statement

---

_includes/back-to-top.html
_pages/law-and-regs/ada.md
assets/js/utils/gaUtil.js
assets/sass/custom/_utilities.scss

This PR adds click tracking to the back to top button and adds the button to remaining law and regs pages.

Back to top updates

---

assets/sass/custom/_touchpoints.scss
assets/sass/custom/_typography.scss

Address #973

---

_pages/notices/_posts/2024-03-08-web-rule.md

Sentence needed to be added to fact sheet.

added disc sentence

---

_pages/index.md
_pages/notices/_posts/2024-03-08-web-rule.md

-removed banner
-added fact sheet to homepage "what's on..."

removed banner etc

---

_pages/_resources/small-entity-compliance-guide.md

Small entity compliance guide

---

_pages/_resources/2024-03-08-web-rule.md
_pages/index.md

Updated What's On to reflect FS movement

updated what's on

---

_pages/file-a-complaint.md
_pages/redirects/communityoutreach.md
assets/js/main.js
assets/js/outreach-campaign.js

This PR uses cookies to enable tracking users who are redirected from ada.gov/communityoutreach to ada.gov and then file a complaint to the portal from ada.gov.

Track complaints filed from outreach

---

_pages/_topics/voting.md

-link pointed to archive site.  this pr fixes that.

corrected link

---

_includes/download-pdf.html
_includes/expand-button.html
_includes/mobile-search-button.html
_includes/print-button.html
_includes/search-box.html
_includes/sidenav.html
_layouts/page.html
assets/js/expand-sidenav.js
assets/js/laws-regs-parser.js
assets/sass/custom/_page.scss
assets/sass/custom/_sidenav.scss
assets/sass/custom/_utilities.scss

This PR moves all the law and regs tooling updates (#778 #782) into one PR and rebases since the main branch has changed a lot since their initial creation.

Law and regs tooling updates

---

_includes/search-box.html
assets/js/laws-regs-parser.js
assets/js/utils/gaUtil.js

This PR adds click tracking to the law and regs in page search feature

Add click tracking to in page search

---

_pages/es/presente-una-queja.md

-Removed fax info from Spanish page

removed fax info

---

_pages/_resources/2024-03-08-web-rule.md
_pages/_resources/small-entity-compliance-guide.md

Removed items from New on ADA.gov feature because they were are no longer new.

removed news items

---

_pages/notices/_posts/2024-08-08-mde-fact-sheet.md

added hyperlinks

---

_pages/file-a-complaint.md

anchor link repair

---

_config.yml

Adds a notice calling out the voting topics page, which links to our existing voting resources.

Voting Notice

---

_pages/_resources/accessibility-govt-websites.md
_pages/_resources/small-entity-compliance-guide.md

requested edits re tag and intro

added tag and language

---

_pages/_resources/accessible-pools-requirements.md
_pages/_resources/commonly-asked-questions-law-enforcement.md
_pages/_resources/law-enforcement-guide.md
_pages/_resources/q&a-accessibility-requirements-pools-public.md
_pages/_resources/returning-servicemembers.md
_pages/_resources/telehealth-guidance.md
_pages/_resources/testing-accommodations.md
_pages/_resources/ticket-sales.md

Tuesday infoline hours were omitted in a few documents.

added Tuesday hours

---

_config.yml

Election is over.  Removed election/voting banner.

removed election banner

---

.github/workflows/preview.yml

Fix the comment for "Preview in Federalist"

Fix pages comment

---

_config.yml
_includes/sidenav.html
_pages/help.md
_plugins/details.rb
assets/sass/custom/_accordion.scss
assets/sass/custom/_collection.scss
assets/sass/custom/_sidenav.scss

- 🌎 The help page will have a series of accordions, including this content
- ⛔ There's no existing box accordion style like this
- ✅ This commit adds the content and style of the accordion
- 🔮 Future commits will add further page content

[FAQ 2] FAQ Box Accordion

---

_config.yml
_includes/sidenav.html
_pages/help.md
_pages/index.md
_plugins/details.rb
assets/sass/custom/_accordion.scss
assets/sass/custom/_collection.scss
assets/sass/custom/_sidenav.scss

- 🌎 We want a FAQ page
- ⛔ There's no place for one on the site, currently
- ✅ This commit adds a new page with urls, title, etc for help
- 🔮 Future commits will add content and styling to this page

Add help/faq content

---

_includes/footer.html

Removes the link to EEO in the footer

Remove EEO footer link

---

_includes/landing/hero.html
assets/sass/custom/_landing.scss

Background: https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/1108

fix: reduce image size

---

_config.yml

added a banner with language re government shutdown

oct1-2025-shutdown
