.circleci/config.yml
.gitignore
.pa11yci
_config.yml
admin/index.html
package-lock.json
package.json

The starter template we are using relies on https://github.com/addyosmani/a11y which is no longer maintained and has not been updated in over four years. This integrates a new a11y CI tool, `pa11y-ci` which is more actively developed and provides additional configuration options that will be helpful in this project.
Lastly, reports of a11y results are now generated for each push and are currently available as an artifact, such as: https://131-346501322-gh.circle-artifacts.com/0/pa11y-results/index.html - this provides a great visual to any a11y issues as opposed to the normal terminal output. In a future PR I would like to find a way to pull this report in as a status check so it's easily accessed for all new pull requests.

Use pa11y-ci

---

_plugins/symlink_detector.rb

Resolve the multiple:
```
** ERROR: directory is already being watched! **
```
warnings being generated while serving Jekyll locally.

Suppress directory warnings

---

_includes/alert-proto.html
_layouts/page.html

This PR adds an alert banner to the overlay pages for user testing. Since we're moving from the sandbox to beta for user testing, DRS wants this banner to call out the site as a work in progress.

Adds alert for user testing

---

_includes/icon-list.html
_pages/understanding/parking.md
_pages/understanding/service-animals.md

Adds the ability to use icon based lists using liquid rather than HTML. Current icons supported: green-check, red-x, error.
Example syntax:
```
{% capture list %}
- one (1) van accessible parking space must be provided
- not required to have a sign with the international symbol of accessibility
- anyone can park in that space | red-x
{% endcapture %}
{% include icon-list.html list=list type="green-check" %}
```

Create icon list component

---

_assets/css/custom/card.scss

Makes the entire card area clickable on the landing page and adds subtle hover effect.

Make entire card clickable

---

_includes/logo.html

Removes comma after Civil Rights Division

Remove comma from site logo

---

_assets/css/custom/page.scss
_layouts/page.html

This adjusts the spacing before headings on the overlay page template, as well as adding the small blue accent beneath `h2`s, and adjusting the side nav link color.

Tweak spacing of elements on overlay page

---

_assets/css/custom/_all.scss
_assets/css/custom/_smooth-scroll.scss

The scroll-behavior property works in most modern browsers. It does not work in Safari or mobile Safari. It also has no IE support.

Add smooth scrolling to supported browsers

---

_includes/landing/report.html
_includes/landing/understand.html
_pages/guides/parking.md
_pages/index.md

The DRS style guide uses title case for headings. We've slightly modified this rule for ada.gov to allow for sentence case when a heading is an independent clause accompanied by punctuation.

Applies DRS style guide to landing page

---

_assets/js/main.js
_assets/js/toc.js
_pages/guides/intro-to-ada.md
_plugins/accordion.rb

This adds a custom Liquid tag for accordions, further abstracting HTML markup out of our markdown files.
Here's what a markdown accordion looks like now (further documentation to come):
```
{% accordion my-unique-id %}
{% collapsible %}
Here's all my **normal** markdown!
{% endcollapsible %}
{% collapsible %}
More content!
{% endcollapsible %}
{% endaccordion %}
```

Add accordion tag

---

_assets/css/custom/_footer.scss
_assets/css/custom/_landing.scss
_includes/card.html
_includes/landing/alert.html
_includes/landing/report.html
_pages/index.md

- Switched "Help us improve ADA.gov" to a heading (h2)
- Made card heading's h3s rather than h2s
- Added aria label to card links so that they are read "Learn more about service animals"
- Switched "How to Report a Disability Rights Violation" headings to h3s
- Added underline to footer links

a11y updates for landing page

---

_assets/css/custom/_sidenav.scss

Allows left nav to be scrollable when there is not sufficient height to show all of the links (on desktop).

Make sticky nav scrollable

---

_config.yml
_pages/guides/mobility-devices.md
_plugins/icon_list.rb

More streamlined approach similar to accordion tag, also allows for large blocks of content to be associated with each bullet rather than only allowing a single line of content.

Add custom icon list liquid tag

---

_assets/css/custom/_page.scss
_assets/css/custom/_sidenav.scss
_includes/sidenav.html
_includes/skipnav.html
_layouts/page.html

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/151
This presents users with two skip nav links - the first will redirect focus to the side navigation containing in-page anchor links, and the second skip nav will allow folks to go directly to the content, bypassing the in-page links.

Add additional skip link for overlay page layout

---

_pages/topics/intro-to-ada.md

Corrects casing of specific title references, in accordance with the DRS style guide:
> Title
> When referring to a specific title of the Americans with Disabilities Act, “Title” should be capitalized.
Example: Businesses that provide goods or services to the public are called “public accommodations” in Title III of the ADA.
Example: DRS’s ADA enforcement work is focused on the statute’s first three titles.

Corrects title casing

---

_pages/topics/intro-to-ada.md

Sorry @hursey013...one more minor update.
This capitalizes `Public` at the beginning of the general requirement.

Upper case on independent clause, public transit

---

_includes/banner-beta.html

The current version, which uses a colon, isn't ideal grammatically. This edit omits the colon and separates the clauses with a period instead.

Minor edit to beta banner punctuation

---

_assets/css/custom/_header.scss
_config.yml
_includes/menu.html
_includes/sidenav.html
_layouts/page.html
_pages/topics/index.md

This converts `ADA Topics` into a dropdown, allowing direction navigation to overlays from the global nav.
It also removes the listing of other overlays within the side navigation, displaying only anchor links within the page currently being viewed.

Enables USWDS dropdown in global navigation

---

_includes/logo.html

Switches title in header back to `ADA.gov` rather than:

Update header title

---

_assets/css/custom/_header.scss

Adds additional space above and below global nav:

Add additional padding to global nav

---

_assets/css/custom/_header.scss
_config.yml
_includes/footer.html
_includes/menu.html
_includes/phone.html

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/187
Adds infoline information to mobile menu flyout:
Also moves the tollfree and TTY numbers to the global config, so that they can be updated in one place.

Add infoline to mobile flyout

---

_pages/topics/intro-to-ada.md

There's a punctuation/line break issue in the Introduction to the ADA `Businesses That Are Open to the Public` section. This PR adds a line break and punctuation (since the other sections have punctuation for the same entry).
```
Applies to:
- Businesses and nonprofits serving the public Examples of businesses and nonprofits include:
```
```
Businesses and nonprofits serving the public.
Examples of businesses and nonprofits include:
```

Adds line break to Intro to ADA

---

_assets/css/custom/_page.scss
_assets/js/main.js
_config.yml
_data/cards.yml
_includes/card.html
_includes/landing/understand.html
_layouts/page.html
_pages/index.md
_pages/topics/index.md
_pages/topics/intro-to-ada.md
_pages/topics/service-animals.md

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/221
Based on @austinhernandez's mockups, this adds a landing page to hold all of the future overlays. It also:
- Removes the drop down list for topics
- Moves the details shown on the card into the page's frontmatter so it can be reused
- Creates a "coming soon" data file to list overlays that are not already published
- Limits the number of overlays displayed on the homepage to 3
Preview:

Add overlay landing page

---

_includes/meta.html

This tag prevents search engines from indexing pages - we will want to remove this prior to launch.

Remove robots meta tag

---

_includes/landing/report.html

Changes homepage button text from `Submit a report` to `File a complaint` for consistency.
We've used "File a complaint" or "Filing a complaint" instead of "Report a violation" or "Submit a report" because we found in keyword analytics more instances of "file" and "complaint" relative to other terms.
> I'm reviewing search keywords to try to determine how users refer to this. It looks like "complaint" and "file a complaint" are the most common, followed by "report," "report a business," etc. The civil rights portal uses the phrase "Report a violation."
> 
> 53. complaint
> 69. file complaint
> 119. complaint form
> 154. file a complaint
> 157. grievance procedure 
> 287. report
> 
> Based on this, I would suggest retaining "file a complaint" for now!

Edits complaint button text for consistency

---

_pages/search.md

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/268
Adds a message that the results are sorted by relevancy.

Add search results sort text

---

_includes/searchgov/form.html

Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/284
I was able to recreate this issue and I definitely feel like it's problematic. I brought it up to the search.gov team and they have it as an identified issue in their backlog.
> Definitely can see how this would be confusing on screen readers. We've thought about (and have an item in our backlog) changing it to "search suggestions" (ex. "2 search suggestions are available" or "No search suggestions") instead of results, which would hopefully be a bit clearer
Until that change is made, I believe the best move is to disable to typeahead functionality.

Disable search.gov typeahead

---

_pages/topics/index.md

Changes: 
`Information for businesses, state and local governments, and people with disabilities`
to:
`Information for people with disabilities, state and local governments, and businesses`

Topics copy change – audience order

---

_config.yml
_includes/landing/understand.html
_pages/topics/index.md

Changes nav text, page heading, and homepage section heading to `Topics` from `ADA Topics`.
The need for concision in the nav list made me think that `ADA Topics` is increasingly redundant. We developed that term as a working label for the overlay content, but now that we have a wordmark and more surrounding content, it seems _possibly_ unnecessary. I'm certainly willing to be persuaded otherwise, but I thought I would send it up to a pull request in the meantime to generate a preview.

Changes 'ADA Topics' to 'Topics'

---

_includes/landing/report.html

This bug was introduced as part of the i18n work, but is fixed in this PR.

Use index for numbering

---

.github/workflows/preview.yml

Update GitHub action to fix the automated addition of the Federalist preview link to the associated pull request.

Fix Federalist Preview link GitHub action

---

_pages/law-and-regs/ada.md

Henry W. has discovered some discrepancies between the original version of the ADA statute and the version we migrated from ADA.gov. These edits bring the beta.ada.gov version in line with the original statute.
Most of the edits are (1) punctuation, primarily the addition of em dashes and (2) removal of redundant `in this section` text. There is one significant edit under Title 47, (3) Telecommunications relay services.
You can see the line edits under the [`Files changed`](https://github.com/usdoj-crt/beta-ada/pull/186/files) tab.

Fixes discrepancies between original ADA statute and ADA.gov version

---

_assets/css/custom/_pagination.scss
_assets/js/templates/pagination/ellipsisTemplate.js
_assets/js/templates/pagination/paginationButtonTemplate.js
_assets/js/templates/pagination/paginationTemplate.js
_assets/js/templates/search/noResultsTemplate.js
_assets/js/templates/search/searchResultsTemplate.js
_assets/js/templates/search/totalResultsTemplate.js
_assets/js/utils/paginationLogic/index.js
_assets/js/utils/renderSearchPage.js
_assets/js/utils/wrapUrls.js
_layouts/page.html

Resolves two issues: https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/363 and https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/364
Styling/Markup Changes:
1. Added hover/focus state changes to pagination buttons and next/previous links. Changes can be seen in _pagination.scss
2. Bolded the ellipses and cleaned up aria roles for them. See ellipsisTemplate.js
3. Added a darker background to the pagination buttons via paginationButtonTemplate.js
4. Added role=status to noResultsTemplate.js this mirrors the aria labels in the total number of results found template. 
5. Added a class to totalResultsTemplate.js to make the text black.
6. Changed the target variable in renderSearchPage.js to .crt-landing--separator_small so that the total results text will …

Pagination button styling and Search page mobile styling.

---

_includes/landing/hero.html

Closes [https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/374](https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/374)
The Problem:
The Solution:
Styling/Markup changes:
1. On the div containing the H1, added 2 classes: tablet-grid-col-6, and desktop-grid-col-8. This will shrink the width of the H1 on tablet devices and will preserve the current width on desktop devices.
2. Added a spacer div below the H1 containing div. Set the aria-hidden attribute to "true" so it is ignored by assistive technology. Added two classes: tablet-grid-col-2 and desktop:display-none. These classes mean that the layout between the H1 and paragraph text is preserved, and that this div is not displayed on desktop devices. 
To test: 
1. Open Federalist link
2. Confirm that new …

Prevent H1 text overflow on tablet devices

---

.pa11yci
_includes/header.html
_includes/landing/hero.html
_plugins/accordion.rb
_plugins/details.rb
package-lock.json
package.json

Changes:
1. Added a `pa11y-skip` class for a11y issues that are manually addressed.
2. So far this class has been added to the following:
a. The homepage H1 and P tags. pa11y flags them because they sit over top of an image. Manual inspection of the text over a white background reveals a AAA rating (WCAG2.1). A minor PR was approved a few weeks ago to add some additional spacing on tablet sized devices so that the text minimally overlaps the part of the image with people in it.
b. The highlighted nav item. Pa11y can't correctly assess pseudo elements, in this case the underline on the current nav location. The line color is the same as the text, and also scores a AAA in contrast (WCAG2.1).
c. Accordion plugin - The button uses a background image for the plus and minus icons. Pa11y can't …

Pa11y update to 3.0.1

---

_includes/scripts.html
package.json

Changes:
1. Added `JEKYLL_ENV=production` to our build script in `package.json`.
2. I did not add a value of 'development' anywhere because [Jekyll assumes that value for the environment if none is specified](https://jekyllrb.com/docs/configuration/environments/)
3. The goal here is to prevent Google Analytics from running when on localhost, so in `scripts.html` I've added an and clause to the if statement that injects the GA script: `if site.ga.ua and jekyll.environment=="production"`

Added production jekyll environment to build script.

---

_assets/css/_uswds-theme-components.scss
package-lock.json
package.json

Changes:
1. package.json - updated USWDS to version 2.12.0
2. package-lock.json
3. Removed "$theme-input-tile-background-color-selected", "$theme-input-tile-border-color" and "$theme-input-tile-border-color-selected" from `_uswds-theme-components.scss` as they are now calculated automatically. 
4. See release manifest here: https://github.com/uswds/uswds/releases/tag/v2.12.0

USWDS upgrade to 2.12.0

---

_assets/css/_uswds-theme-components.scss
_assets/css/custom/_search.scss
_assets/css/overrides/_external-link.scss
package-lock.json
package.json

Changes:
1. package.json - USWDS version upped to 2.12.1 - Update manifest: https://github.com/uswds/uswds/releases/tag/v2.12.1
2. package-lock.json updated accordingly
3. Updated _search.scss file to address new search icon display issue that occurred as a result of the update.
4. Updated our _external-link.scss override to match new design options
5. Added default values to the options for the external link mixin arguments to make them optional. This gets around an issue where the external link mixin called by USWDS provides no arguments, but our override expects four.

USWDS upgrade to version 2.12.1

---

_assets/css/custom/_buttons.scss

Problem:
The Print button doesn't change color when hovered with a mouse or when receiving keyboard focus. 
Changes:
1. Added rules to _buttons.scss for the #crt-page--printbutton. 
- Assigned a background color
- Assigned a hover state color that is in line with our style guide
- Assigned a focus state color that is in line with our style guide
Closes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/392

Added styling rules to provide a hover and focus state to the print button

---

_includes/searchgov/form.html
package-lock.json
package.json

Changes:
1. Package.json - updated USWDS to version 2.12.2
2. The search icon is missing on screen sizes < desktop. Added markup recommended from USWDS version 2.13 to fix. That markup was added to the forms.html file.

Updated to version 2.12.2. Fixed missing search icon.

---

_includes/notice.html
_pages/notices/_posts/2021-08-25-covid-qa.md

Changes:
1. Added new frontmatter fields to the COVID QA page. `notice_text` and `notice_text_es`. Previously we referred to the page title, but since that is no longer appropriate I created a new field to reference in both the English and Spanish translations. Note: Spanish translation text will be updated asap.
2. In `notice.html` The anchor tag now references the two new fields mentioned above.

Covid banner and page title changes

---

_includes/banner-beta.html
_includes/banner.html
_includes/footer.html
_includes/header.html
_includes/logo.html
_includes/notice.html
_includes/phone.html
_includes/redirect-modal.html
_includes/touchpoints.html
_pages/es/presente-una-queja.md

Rationale:
1. To bring our translated page into alignment with suggestions from the LEP (Low English Proficiency) website recommendations, we have opted to only show the body content of the page in Spanish.
Changes:
1. The 'lang' variable is set to 'en' in the following components: `banner.html`, `banner-beta.html`, `footer.html`, `header.html`, `logo.html`, `notice.html`, `phone.html`, `redirect-modal.html`, `touchpoints.html`
2. This change ensures that the components will only pull in data from the english i18n file, and also only the english names and urls for navigation.
3. `header.html` has another change in it for setting the active class on the current navigation link. Since we only have one page at the moment we are just saying "If the basedir is "es" and you're on the …

Translate Body Copy only

---

_assets/css/custom/_buttons.scss
_assets/css/custom/_search.scss

Rationale:
1. Screen reader only text doesn't have proper color contrast in mind, nor is it relevant, however Axe Dev Tools and Wave accessibility checker don't know this. Waves flags it as an error because the absolute positioning of the text is removed when the site is checked, thus the text then overlays the other elements and causes a contrast error.
Changes:
1. _buttons.scss - added a rule for span.usa-sr-only class specifying that the text be black.
2. _search.scss - added a rule for label.usa-sr-only class specifying that the text be white.
Testing:
1. Open the preview page and run Waves and Axe Devtools. No errors should appear.

Screen reader text passes contrast checks

---

_includes/meta.html

Rationale:
1. According to Google, to properly have alternate language pages indexed, both the translation and the original page need to be listed in the `<head>` tag. [Link](https://developers.google.com/search/docs/advanced/crawling/localized-versions#html)
Change:
1. In `meta.html` the condition `item.lang!=lang` was removed from the if check for the alternate languages.
Test:
1. In the preview, check the meta tags within the head section. On pages with a translation available (file a complaint, presente una queja) both the current page and it's translation should be listed in the head section as alternate language link tags.

Small change to properly link alternate pages for i18n.

---

_includes/meta.html

Changes:
1. In meta.html changed the nonexistent 'relative' liquid filter to 'relative_url'
Test:
1. Meta content should contain proper urls now.

Changed relative to relative_url

---

_data/en/i18n.yml
_data/es/i18n.yml
_includes/footer.html
_includes/logo.html

Changes:
1.  Added new data field to both the spanish and english translation files: `doj_seal`
2.  Added this field to the `logo.html` and `footer.html` `_includes` files
3.  Alt text is taken from the justice.gov website alt text and reads: "The United States Department of Justice"

Added alt text for the seal logo

---

_config.yml
_includes/scripts.html
_includes/skipnav.html
_layouts/page.html
_pages/law-and-regs/index.md
_pages/resources.md
_pages/topics.md
tests/menu-button-mobile.spec.js

@chinelo-ikejimba Caught that the h1's on each page were not updated to match the new navigation terms. This Pull Request fixes that. The 'title' field in the front matter of each page now matches the title item in the _config.yml file.

Updating h1s to match new navigation terms

---

_includes/card.html
_includes/landing/alert.html
_includes/landing/report.html

Three IDs were added to specific elements on the home page:
1. gtm-feedback-link
2. gtm-file-compliant-button
3. gtm-service-animals-card
Each of these ids will be referenced in the Google Analytics console to fire visibility trigger events when they are 100% visible to users.

IDs for Home page elements

---

Gemfile.lock

Bumped Rack version to 2.2.3.1
To test:
1. Pull down branch
2. Build and test locally 
3. Confirm no issues in Jekyll build
4. Confirm no issues in Federalist preview

Bump rack version to 2.2.3.1

---

_assets/js/main.js
_assets/js/modal.js
_assets/js/redirect-modal.js
_assets/js/search.js
_includes/scripts.html
webpack.config.js

modal.js and redirect-modal.js are now named functions that are called in each file. They are now built by webpack. They function identically to before the migration to Webpack. 
To test:
1. Open the preview url below
2. Open a link to an external page (you can try the Adobe Stock image link in the homepage footer)
3. Confirm that the modal works as on the existing beta.ada.gov site

Moving modal and redirect modal out from Jekyll build pipeline into Webpack

---

_assets/css/custom/_buttons.scss
_assets/css/custom/_sidenav.scss
_includes/download-pdf.html
_includes/print-button.html
_layouts/page.html

[Github Issue](https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/512)
The text content of the Download PDF button now reads: "Download PDF Guidance" and is styled as a button all the time rather than becoming a hyperlink at lengths of greater than 15 characters.
Before:
After: 
+ [ ] Confirm the styling looks as expected
+ [ ] Confirm the button still downloads the pdfs
+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests …

Changing styling and text of download pdf button.

---

_assets/css/custom/_print.scss

[Ticket](https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/509)
Currently, when one attempts to print a page with the "Open all Sections" button present, the button appears on the printed page as well, even thought it is irrelevant to that view. This PR removes that button from the printed page.
Not applicable.
+ [ ] Attempt to print a page with an Open all Sections button on it: State and Local Governments, Frequently Asked Questions about Service Animals, or Business that are open to the public.
+ [ ] Confirm that both in the preview and in the printed document the Open all Sections button is not present, but that it is present on the page before and after printing.
+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any …

Hide Open All Sections button on Print

---

_assets/css/custom/_print.scss
_includes/notice.html

[Ticket](https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/516)
Currently, when one attempts to print a page the COVID banner also prints. This banner is unhelpful on printed pages. This pull request hides the banner when printing a page.
Not applicable.
+ [ ] Attempt to print a page, confirm the COVID banner is not on the page.
+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests …

Hide COVID warning banner on print

---

package-lock.json

[Original PR from Dependabot](https://github.com/usdoj-crt/beta-ada/pull/339)
This updates the terser package (used in minifying JS) from 5.11 -> 5.14.2 and in doing so resolves some security vulnerabilities.
Not applicable.
+ [x] Test JS on site and make sure production build is minified.
+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).
+ [ ] If this is a story, run locally and check to make …

Updated terser package to 5.14.2

---

_assets/css/custom/_print.scss

[Ticket](https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/509)
Currently, when one attempts to print a page with the "Open all Sections" button present, the button appears on the printed page as well, even thought it is irrelevant to that view. This PR removes that button from the printed page.
Not applicable.
+ [ ] Attempt to print a page with an Open all Sections button on it: State and Local Governments, Frequently Asked Questions about Service Animals, or Business that are open to the public.
+ [ ] Confirm that both in the preview and in the printed document the Open all Sections button is not present, but that it is present on the page before and after printing.
+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any …

Hide Breadcrumbs on Print

---

_assets/css/custom/_print.scss

[Ticket](https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/511)
The + and - icons on the accordion elements are not displayed properly when printing a page. This pull request changes the styling so the icons are not displayed at all when printing.
Old:
New:
+ [x] Attempt to print a page and confirm that the accordion elements don't have any + or - icons visable.
+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests …

Hide background images of accordions when printing the page

---

_assets/js/utils/constants.js

The tags were not added to the constants.js file for mobility devices or medical care. They have been added so that filtering now works.

Adding mobility devices and medical care to tags list to make JS work  on guidance page.

---

_assets/sass/custom/_header.scss
_config.yml
_pages/cases.md
_pages/law-and-regs/index.md

1. Moved the /cases page from under /law-and-regs to top level
2. Added new Nav item - Enforcement that points to /cases
3. Changed H1 on /cases page
4. Changed short title of Featured Topics
5. Cut size of search bar down
6. Removed verbs from the titles in the main nav

Move Cases page to Enforcement

---

_assets/js/utils/constants.js
_plugins/figures.rb

This adds a new mark down widget that allows users to add in figures and figure captions.
You can still add figures using standard HTML. But this syntax is a little shorter. 
To use it:
{% figure %}
This can be whatever figure content you want. Add images like so:
{% assets path-to-image alt="alt text" %}
{% endfigure %}
If you want to add a caption, do it like so:
{% figure %}
This can be whatever figure content you want. Add images like so:
{% assets path-to-image alt="alt text" %}
{% figcaption %}
Some text!
{% endfigcaption %}
{% endfigure %}
If you want to add a title to your figure, add it like this:
{% figure MyTitle %}
This can be whatever figure content you want. Add images like so:
{% assets path-to-image alt="alt text" %}
{% figcaption %}
Some text!
{% endfigcaption %}
{% …

New markdown widget for creating html figures

---

_config.yml

And also to remove the old search.gov configuration values. 
This change has no corresponding frontend changes.
To test:
- Run locally and head to localhost:4000/sitemap.xml
- Confirm that /admin is not in the sitemap.xml file
- Check that /admin is not in the sitemap.xml file at the Federalist Preview URL either

Updating the Configuration file to hide Netlify CMS admin page from Sitemap

---

_assets/sass/custom/_touchpoints.scss

Super small alignment fix for the text on the Feedback page. 
How it used to look:
How it looks now:

Fixing left alignment of text on feedback page

---

_assets/sass/custom/_search.scss
_includes/header.html
_includes/searchgov/form.html

Reason: The search icon is currently a bit ambiguous, and it's meaning is not clear.
By explicitly stating 'Search' in the search bar, we hope to remove any ambiguity about the button's function.

Updating Search button to include the text "Search"

---

_assets/js/templates/badges/badgeTemplate.js
_assets/js/utils/constants.js
_data/tags.yml
_includes/category-selector.html
_layouts/default.html
_pages/_resources/2021-08-25-covid-qa.md

Addresses concern in this ticket: https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/607
Changes:
1. Moved the COVID 19 notification to under /resources
2. Added COVID-19 filter
3. Added page description to COVID 19 page
4. Added redirect to COVID 19 page
5. Removed COVID 19 banner

Covid page moved to resources page

---

_includes/breadcrumbs.html
_layouts/default.html
_pages/notices/_posts/2022-11-02-upcoming-changes.md

Changes:
1. Updated banner notice to read: "Soon beta.ADA.gov will become the new ADA.gov. Learn what to expect"
2. Added a new page titled "Upcoming changes to ADA.gov" to help explain upcoming changes to the site.
3. Updated the breadcrumbs component to hide unneeded month, date and year links.

Change is coming messaging

---

Gemfile.lock

Addressing dependabot issue. 
Upgrading nokogiri version from 1.13.6 to 1.13.9

Bump Nokogiri to 1.13.9

---

_includes/landing/learn.html
_includes/landing/service-animals.html

Alignment of list items on homepage deviated from original design mocks. This has been fixed in this PR.
Note the alignment in the Design mocks:
Note the current alignment:
And here is the fixed alignment:

Fixing minor alignment issue of list items

---

_assets/js/utils/constants.js
_config.yml

Changes:
1. Updated search params in the config.yml file
2. Updated search params in the constants.js file
Both of these changes handle the initial search and then the search pagination.
Search.gov has fully indexed each site (ada.gov and archive.ada.gov).

Updating search params to remove beta search

---

_assets/js/click-tracking.js
_assets/js/templates/search/searchResultsTemplate.js
_assets/js/utils/constants.js
_assets/js/utils/renderSearchPage.js
_includes/scripts.html
_pages/search.md
webpack.javascript.js

What's changed?
We're adding click tracking to our search results so we can update search.gov with popularity scores for our search results.
This adds an onclick event for each link on the search results page and sends the following info to Search.gov:
- url clicked
- search query
- affiliate
- position
- module code
- access key
We aren't doing anything with the response at the moment.
No front-end design changes. 
To test: 
1. Fire up locally
2. Let me know so I open the search.gov click tracking admin console
3. Enter a search query
4. Check the console to make sure there are no errors logged
5. Click a link
6. Let me (Jack Ryan) know 
7. I'll confirm that the number of clicks listed in the admin console has increased by the number of links you've opened

Adding click tracking to search results

---

_includes/scripts.html

Pretty straightforward. 
If the jekyll environment is development (the default), don't include the Google Analytics and Digital Analytics Platform scripts.
The reason we don't have to explicitly state the environment for production is that it is set here by Federalist: [https://github.com/cloud-gov/pages-build-container/blob/6f9c2a2ee010c33c290f706325848c5db7fbb503/src/steps/build.py#L405](https://github.com/cloud-gov/pages-build-container/blob/6f9c2a2ee010c33c290f706325848c5db7fbb503/src/steps/build.py#L405)

Only include GA and DAP scripts on production

---

.github/workflows/a11y.yml
.github/workflows/linter.yml
_includes/notice.html

Ok so there are a few changes in here.
1. Pa11y-ci stopped working on ubuntu-latest (22.04.1) so we're bumping the image version down to 20.04 as per this issue: [https://github.com/pa11y/pa11y-ci/issues/198](https://github.com/pa11y/pa11y-ci/issues/198)
2. We're getting a false alarm on the color contrast in the notice banner. Axe is claiming the anchor text is not high enough contrast. I can't replicate this error using Waves, IBM Equal Access Accessibility Checker, or Axe Devtools in the browser. Using Colour Contrast Analyzer, seems we're in the clear as well. See screenshots below:
No hover: 
Hover:
So I added the .pa11y-skip class to skip that element.
3. I upgraded the actions/checkout steps to use v3 because Github keeps yelling at us.
All seems well now.

Downgrade Ubuntu version in a11y action to 20.04

---

package-lock.json

Pretty straightforward, make sure to run `npm install` in your main branch once this is merged in.
Bumped json5 and babel-loader to latest versions to address security vulnerabilities in each.

Updated babel-loader and json5 packages to latest

---

_assets/sass/custom/_sidenav.scss
_pages/law-and-regs/title-iii-regulations.md

- 🌎 Pages have "download" and "print" buttons for users who don't want to view the pages online.
- ⛔ On pages where the TOC takes up the full height, users have to scroll to the bottom of large documents to see the buttons.
- ✅ This PR fixes that by having the sidenav give room when in desktop mode. Mobile mode is unaffected.
- 🔮 Future PRs will add links to download their PDF equivalents
Before:
After:

Leave room for action buttons on the sidenav

---

_assets/sass/custom/_page.scss
_layouts/page.html
_pages/cases.md
_pages/law-and-regs/design-standards/index.md
_pages/law-and-regs/index.md
_pages/notices/_posts/2022-11-16-ada-launch.md
_pages/search.md

- 🌎 As pointed out by Tina, some pages on ada.gov feel difficult to read.
- ⛔ Her theory is that this is because the text width is too large
- ✅ This commit explores shrinking that width to 64rem (the "small screen" max width used throughout the site)
- 🔮 This is a draft to evaluate whether this would make pages more readable - feedback is encouraged!
Before: scanning the line:
> Knowing when the 1991 or the 2010 ADA Standards apply to buildings and facilities is important in determining if your building or facility complies with the ADA. The [ADA Requirements: Effective Date and Compliance Date guide](https://archive.ada.gov/revised_effective_dates-2010.htm) helps to explain which version of the ADA Standards to use and when.
is difficult because the eye has to travel far on large …

Limit page width to improve readability.

---

_assets/sass/custom/_page.scss
package-lock.json

This fixes an issue on very large screens, where the alignment for the new compact pages was off (see GIFs below).
- 🌎 Compact pages don't stretch to fill the screen
- ⛔ On large screens, this means they are limited to the left 64rem of the screen
- ✅ This commit auto-aligns them in the center, in the same was as the toolbar.
Before:
(The misalignment is only on the large resolution - other resolutions are unaffected)
After:
(All resolutions look good now!)

Fix compact alignment on large screens

---

_assets/js/redirect404.js
_assets/sass/custom/_site_alert.scss
_includes/alert.html
_includes/common-alert.html
_includes/ta-link-back.html
_layouts/full.html
_layouts/page.html
_pages/404.md
_pages/resources.md

Started as an offshoot of #450 
🌎 There is a summary box on the resources page and no alert on the 404 page.
⛔ The summary box does not effectively highlight the information.
✅ This PR adds an alert component and includes it on the resources and 404 page to better highlight text.
**Before**
**Resource page**
**404 page**
**After**
**Resource page**
**404 page**
https://user-images.githubusercontent.com/18104884/212182738-8b4022c0-593b-430e-8274-9ff97ddd1c85.mov
**Test plan**
Navigate to the resources page and verify that the alert component looks as expected on desktop and mobile.
Navigate to a known redirect (i.e. /ada_title_I/) and verify that when you see the 404 page before being redirected the new alert is visible.
Navigate to a known 404 (i.e. /xyz/) and verify that the alert is not …

Adding new alert component to 404 page and resources page

---

_assets/sass/custom/_page.scss

This is a quick followup to the previous PR (https://github.com/usdoj-crt/beta-ada/pull/479) which missed an issue that affected the compact view at narrow resolutions:
- 🌎 We try to align compact pages with the title bar
- ⛔ Right now this is causing the page to move off of the screen on specific (narrow, desktop) resolutions, as we're using position: relative with a definite right margin with certain widths.
- ✅ This commit changes the approach to force the page to the same width as the title bar at all times (95rem) but with padding to align it properly
Before:
After:

Fix page offset at narrow resolutions

---

admin/config.yml

A straggler of the federalist -> pages.cloud.gov change
- 🌎 Federalist is now cloud.gov pages
- ⛔ This url is on the old federalst structure
- ✅ This commit moves it to pages.cloud.gov

Update our auth endpoint away from federalist

---

_assets/sass/custom/_utilities.scss
_includes/landing/service-animals.html
_pages/index.md

Rearrange content types on the homepage to match https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/641#issuecomment-1428630799
- 🌎 The site offers, in increasing levels of technical language, Featured
Topics, Resources, and Laws & Regulations.
- ⛔ These are out of order on the homepage as is - that is, resources
are the "step up" from topics, and laws & regs from that.
- ✅ This PR reorganizes them and updates some wording.
Full demo across desktop/mobile/large screen:

Rearrange content types on the homepage.

---

_assets/js/netlify/generateChildElements.js
_assets/js/netlify/makeHTMLFromBodyContent.js
admin/index.html
package-lock.json
package.json

This diff addresses style and html react rendering errors in Netlify so they do not break the page.
1.  Navigate to "/admin/"
2.  Click on a previously broken article in a collection (i.e. the Guide to Disability Rights in the Resources collection)
3.  Verify that the html tag error is handled and preview appears unbroken
4.  Click on a previously broken article in a collection (i.e. Restriping Parking Spaces in the Resources collection)
5. Verify that the style prop error is handled and preview appears unbroken
**Before**
**After**

Address Netlify errors

---

_pages/index.md

Credit to @nguyen-tina for the catch!
This homepage link is broken:
This PR fixes it!

Fix broken service animals link

---

_includes/related-content.html

This PR filters the title ii and title iii tags from the related content boxes to make them more relevant to the page.
**Before**
**After**
**Test Plan**
Spot check the pages on the site to verify that the related content box is functioning as expected.

Filter title ii and title iii tags from related content

---

_assets/js/netlify/generatePageData.js
_assets/js/netlify/makeHTMLFromBodyContent.js
_assets/js/netlify/preview.js
_assets/js/netlify/renderMdWidgets.js
_config.yml
_plugins/site_json.rb
admin/config.yml
admin/index.html

cc: @vwilliamsn @c2nelson 
This adds support for rending HTML includes.
It turns out a lot of the includes depend on _site variables_, such as what other posts exist and what those posts include. For example, to render news items, you need to know what news pages exist. That's something netlify doesn't know about, because netlify only cares about the current page.
Because those exist in the Jekyll context prior to loading our site, it's not possible (or at least, it's very difficult) to include a version of those variables for Netlify to parse. This means that includes which depend on other components (like the news feature) will fail to load.
Some of the listed includes also depend on _layouts_ being supported, but we don't support them yet. The includes themselves should work, but we …

[Netlify] Render Includes components without variables

---

.gitignore
_config.yml
scripts/print_dates.sh

As discussed with @c2nelson during pairing, this will make finding the commit date for files easier.
- 🌎 Search engine recency requires accurate commit dates.
- ⛔ Right now, other results are prioritized over our dates because we don't have up-to-date numbers to give them.
- ✅ This commit adds a script to gather commit dates.
- 🔮 Future commits can expand on this to gather other automated info that we need for site content management.
[dates.csv](https://github.com/usdoj-crt/beta-ada/files/11140428/dates.csv)
Example output:

Add a script to find dates

---

_assets/js/netlify/loadSiteData.js
_assets/js/netlify/preview.js
_assets/js/netlify/renderMdWidgets.js
_config.yml
_includes/page.json
site.json

Exposes site information to netlify - see the screenshots for an example of what this enables.
- 🌎 Right now, Netlify only gets information about the current page. It
doesn't know about other pages.
- ⛔ This isn't great because some pages (such as the news widget, or
featured topics widget) require knowledge about other pages on the
site to render.
- ✅ This PR exports as much site data as we can reasonably export
to Netlify.
Also fixes a bug:
- 🌎 Sometimes quotes exist in variable image paths
- ⛔ Our code wasn't accounting for that
- ✅ This commit trims the quotes
More of a note-to-self, here's the sheet I used to evaluate whether I got all of the places we use site information:
[Site Vars Support.xlsx](https://github.com/usdoj-crt/beta-ada/files/11389747/Site.Vars.Support.xlsx)

Make site-wide info available to Netlify

---

.pa11yci-desktop

We've been getting too many false alarms. I'd previously turned off mobile, but desktop is acting up, too.
See: github.com/pa11y/pa11y/issues/633

Turn off pa11y color-contrast

---

_assets/js/netlify/makeError.js
_assets/js/netlify/makeTemplate.js
_assets/js/netlify/preview.js

- 🌎 The netlify system breaks entirely if a template is invalid.
- ⛔ This isn't great because as you're typing a template out, it's invalid.
- ✅ This commit catches those exceptions and displays them nicely.

Don't stop rendering on template failures.

---

_data/generated_redirects.json
_includes/sitemap-pages.html
_pages/redirects/site_map.md
_pages/site_map.md

Currently www.ada.gov/site_map redirects to the archive site. This PR adds a sitemap page on the new site and removes the redirect.

Add sitemap page and remove redirect to archive site

---

_assets/js/utils/gaUtil.js
_includes/card.html
_includes/landing/learn.html
_includes/notice.html
_includes/page-type-info-box.html
_includes/related-content.html
_includes/subnav.html

This PR adds more click events to measure user interaction with home page navigation elements, topic cards, related content boxes, etc.

Add GA click events to navigation elements

---

_assets/js/expand-sidenav.js
_assets/js/main.js
_includes/expand-button.html
_layouts/page.html

This PR adds an expand all button to the sidenav to enable viewing all the submenus at once.

Add expand all button to sidenav

---

_assets/js/expand-sidenav.js
_includes/expand-button.html
_layouts/page.html
_pages/law-and-regs/design-standards/1991-design-standards.md
_pages/law-and-regs/design-standards/2010-stds.md
_pages/law-and-regs/title-ii-2010-regulations.md
_pages/law-and-regs/title-iii-regulations.md

This PR addresses a bug where the expand all button was not working and appearing on pages other than the laws and regs/design standards. It also updates the spacing between the expand all button and the other buttons.

Expand all bug fix

---

_includes/download-pdf.html
_layouts/page.html
_pages/_resources/ai-guidance.md
_pages/_resources/opioid-use-disorder.md
_pages/_resources/web-guidance.md
_pages/law-and-regs/design-standards/1991-design-standards.md
_pages/law-and-regs/design-standards/2010-stds.md
_pages/law-and-regs/design-standards/standards-guidance.md
_pages/law-and-regs/title-ii-2010-regulations.md
_pages/law-and-regs/title-iii-regulations.md
admin/config.yml

Re: https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/813#issuecomment-1612991724
- 🌎 Right now the button can only say "Download PDF Guidance"
- ⛔ We want to make buttons for non-guidance downloads
- ✅ This commit enables that, and adds flags to edit it in netlify

Make Download PDF text configurable

---

_includes/landing/learn.html

Make "learn more" links read correctly for screen readers.
- 🌎 These learn more links show up on the landing page. Right now, they have static aria-labels.
- ⛔ This means that they're all read as "learn more example link" to screen readers.
- ✅ This commit removes the aria labels, meaning the link text will be read instead (see example below)
| Before | After |
|--------|--------|
| ![example with reader showing bad aria-label](https://github.com/usdoj-crt/beta-ada/assets/15126660/933aab24-99f1-4d27-9f7c-5f17f065ac90) | ![Example showing reader reading links without label](https://github.com/usdoj-crt/beta-ada/assets/15126660/55552aaa-9358-4fa8-bc85-acbd6c89d725) |

Remove aria-label from learn more

---

_assets/js/utils/gaUtil.js
_includes/landing/learn.html

- 🌎 The aria-label was used to provide an event name
- ⛔ Aria-label doesn't make sense for all links, and was removed.
- ✅ This commit re-adds an event name without an aria-label

Analytics: Re-add link tracking to the learn more links

---

_assets/js/netlify/makeHTMLFromBodyContent.js
admin/config.yml
admin/index.html

Currently there is a bug where Netlify is adding a \ character in front of links causing them to break. This PR adds JS to remove that character when the entry is saved on Netlify.
It also updates the Netlify config to correctly pull entries under notices.

Netlify internal link bug fix

---

_assets/js/feature-flag.js
_assets/js/main.js
_assets/js/netlify/preview.js
_assets/js/utils/gaUtil.js

This PR enables feature flags to show features only to users who have logged into Netlify by adding a session variable. It also adds A/B testing capabilities by randomly assigning cookie A to 50% of users and cookie B to the other 50%.

Add feature flag and a/b testing

---

_assets/js/expand-sidenav.js
_assets/sass/custom/_buttons.scss
_assets/sass/custom/_sidenav.scss
_config.yml
_includes/download-pdf.html
_includes/expand-button.html
_includes/header.html
_includes/print-button.html
_includes/sidenav.html
_layouts/page.html

This PR moves the print, download, and expand buttons to the top of the sidenav and adds the ADA, Title II, Title III, and Design Standards to the top nav:

Update sidenav and top nav

---

_assets/js/feature-flag.js
_assets/js/netlify/preview.js
admin/index.html

This PR updates the logic for the feature flag to use a checkbox selection rather than a window event listener. Checking the box will allowlist the Netlify user on the feature and unchecking it will blocklist them. Once the session expires the user will blocklisted until they check the box again.

Add checkbox to admin page for feature flags

---

.github/workflows/linter.yml
.markdown-lint.yml
_assets/js/laws-regs-parser.js
_pages/_resources/access-911.md
_pages/law-and-regs/design-standards/1991-design-standards.md

This PR fixes two issues with the law and regs copy/print functionality:
1. Resolves a bug where the user was directed to a 404 page after printing
2. Opens accordions when copying and printing so all content within the accordions is captured.

Update copy and print for law and regs

---

_assets/js/main.js

Note: A long term solution to this should be done in https://github.com/uswds/uswds/issues/4338
- 🌎 Some of our pages have a few hundred tooltips
- ⛔ USWDS assigns them all random ids, but the ids sometimes conflict! Especially on ci/cd, the random number generator is bad and conflicts happen dependably.
- ✅ This commit attempts to patch the issue by modying the ids after they've been
generated
- 🔮 Future commits should remove this once upstream is fixed

Patch Conflicting Tooltips

---

_assets/sass/custom/_touchpoints.scss

This PR updates the touchpoints survey styles to remove excess padding and make the text and border contrast more so it's not missed.
**Before**
**After**

Update page helpful touchpoints survey styles

---

_includes/landing/hero.html
assets/sass/custom/_landing.scss

This PR tries to mitigate a Layout Shift issue [issue](https://lookerstudio.google.com/u/0/reporting/bbc5698d-57bb-4969-9e07-68810b9fa348/page/9WDQB?params=%7B%22origin%22:%22https:%2F%2Fwww.ada.gov%22%7D) by setting widths for the hero image loading on the page.

Add height to hero image

---

assets/sass/custom/_landing.scss

The hero height was too short of the text on some resolutions. This PR fixes it.

Fix hero height

---

_data/manual_redirects.json

- 🌎 We recently changed the URLs for title ii and title iii
- ⛔ This causes problems for folks with bookmarked pages
- ✅ This commit adds a manual redirect from the old urls to the new ones.
Note that this will still result in 404's in the logs. They are redirected following the 404 via javascript.

Add title ii and iii to manual_redirects

---

assets/js/utils/expandAccordions/getAccordions.js

The expand-accordions-wrapper currently doesn't work with the accordion component because the id matching JS to find the accordion content is looking for the incorrect id. This PR fixes that.

Fix bug with expand accordions wrapper

---

_includes/back-to-top.html
_includes/touchpoints.html
assets/sass/custom/_utilities.scss

- 🌎 "Give us feedback" is set to display:none on mobile
- ⛔ We want to get feedback from mobile users
- ✅ This commit shows the feedback button, and repositions / resizes "back to top" to be a larger touch target
Tablet:
Mobile:
Desktop:

Adds the "Give Us Feedback" button to mobile

---

_includes/breadcrumbs.html

Re: https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/985
- 🌎 The notice breadcrumbs show links to the year, month, etc of the notice
- ⛔ These pages don't actually exist, so those links 404
- ✅ This commit removes intermediate breadcrumbs for notices pages, so it now shows "Home > Notice title"
Notice page: <img width="1007" alt="image" src="https://github.com/usdoj-crt/beta-ada/assets/15126660/cbb68851-c0ea-4efc-8552-9f3535cc91bf">
Non-notice page: <img width="787" alt="image" src="https://github.com/usdoj-crt/beta-ada/assets/15126660/27722c44-0f77-4da7-88e5-9ccfb057be0b">

Remove intermediate breadcrumbs for notice pages

---

_config.yml

The AG signed the MDE rule.  Replaced the anniversary signing link with the press release re the rule.

mde press release link added to banner

---

assets/js/expand-sidenav.js

This PR fixes a bug where the in page search was not working on /law-and-regs/ada/ because of an error with the expand button not being found on the page.

Fix in page search on ada page

---

_config.yml
_includes/sidenav.html
_pages/help.md
_plugins/details.rb
assets/sass/custom/_accordion.scss
assets/sass/custom/_sidenav.scss

- 🌎 This content goes in the new help/FAQ page
- ✅ This commit adds a list of links between topics and relevant standards sections

[FAQ 4] Add content for help resources

---

_includes/header.html
_includes/landing/hero.html
_pages/index.md
assets/sass/custom/_landing.scss

This pull request implements a news content widget for use on the homepage. It is currently defined in index.md underneath the 'hero' section and is part of the hero template html.
Note: The content in the news content module in this PR is currently placeholder. Currently it links to: https://www.justice.gov/crt/our-work

[ADA-1096] News Content Widget

---

.github/workflows/content-grid.yml

The content grid is failing to publish because of a deprecated "upload artifacts" action.
This upgrades the action.

Upgrade content grid to v4

---

.github/workflows/a11y.yml

Ubuntu version 20.04 is deprecated and has a scheduled brownout for today, meaning this workflow will fail. I have updated the Ubuntu version used by this workflow to `ubuntu-latest` as recommended.

Update accessibility workflow a11y.yml to use non-deprecated versions
